max-window-clicks-per-second: 20
kick-player: true

boss-timer:
  interval-millis: 3600000
  next-spawn-millis: 0

whitelist-pickaxe:
  blocks: []

spawn-movement-protection:
  enabled: true
  region-id: spawn

forward-teleport-wall-check:
  enabled: true
  ray-step: 0.2
